### PR TITLE
Add Contact Serializer

### PR DESCRIPTION
**Pull request by dgiltz**
# Summary

Added a serializer in the contacts as a method
	
## Test Plan

How did you test your changes?

## Related Issues

Which issues does this PR resolve/work on?
Closes #

### CODE REVIEW

**Comment by CurtisMIT** [comment]
@dgiltz I added the serialize property in #92 already, sorry for forgetting to mention it.
https://github.com/hack4impact-mcgill/mu-crm-tool/pull/92/files#diff-96c5a7997e3d147589c1d6cac9cf36730df0fe459ae0170a2fc90ededd63fed2R128

**Comment by dgiltz** [comment]
Oh ok, I'll just get rid of the pull request then, and I can add them if you're busy

**Comment by CurtisMIT** [comment]
Oh I already added them lol, feel free to review my pr!
https://github.com/hack4impact-mcgill/mu-crm-tool/pull/92/files#diff-96c5a7997e3d147589c1d6cac9cf36730df0fe459ae0170a2fc90ededd63fed2R128

**Comment by dgiltz** [comment]
RIP, and will do

**Pull request closed without merging**
