### PR TITLE
removed contact filler and set up migrations

### PR DESCRIPTION
**Pull request by CurtisMIT**
# Summary

I've deleted the Contact filler class and set up migrations with Flask-migrate.

# Details
- Contact is currently bidirectional with Project.

## Test Plan
- Manually tested migration commands.

## Related Issues
N/A

### CODE REVIEW

**Comment by celinehuang** [comment]
Did you check if the tables are on PGAdmin?

**Comment by celinehuang** [comment]
Code looks good, I will also pull your branch and run the migration but next time maybe a screenshot of the tables is a good idea!

**Review by celinehuang — COMMENTED** [review]
Code looks good, I will also pull your branch and run the migration but next time maybe a screenshot of the tables is a good idea!

**Comment by dgiltz** [comment]
Couldn't see anything wrong looking it over! Looks good to me

**Comment by celinehuang** [comment]
image

Am I doing something wrong lol

**Comment by CurtisMIT** [comment]
@celinehuang Oh it's not you, it's me, I missed it mb. Gonna fix it and screencap the tables as well.

**Review by celinehuang — APPROVED** [review]
😰 🥵

**Pull request merged**
