### PR TITLE
New migration to remove the unique=true for donation.email

### LINKED ISSUE #127: New migration to fix donor.email(unique=false)
Follow up to issue #126

### PR DESCRIPTION
**Pull request by peterghrong**
# Summary

Since the `Donation.email(unique=true)` constraint is removed, I added a new migration so the db is up to date
	
## Test Plan

Checked on pgadmin with removed unique constraint
Screen Shot 2021-02-15 at 1 44 37 PM

Pic below only for reference, I don't think the unique constraint will show up here regardless though. 
Screen Shot 2021-02-15 at 1 45 00 PM

## Related Issues

Which issues does this PR resolve/work on?
Closes #127

### CODE REVIEW

**Review by CurtisMIT — CHANGES_REQUESTED** [review]
@peterghrong The migration looks good but for #126, is it possible to make a change to the name of your function `get_donation_amounts_by_email`, as it seems like you're treating the `email` attribute as a optional argument, similar to how we did it for projects' type, unless you want it to be specifically used through filtering by emails only. Another thing are the two validity checks within the function, I feel like the first check can be removed as the future create a donation pr should include a check for `""` there, or maybe you can modify the abort messages as they're exactly the same currently.

**Comment by celinehuang** [comment]
I changed the PR title just so it's clearer

**Comment by CurtisMIT** [comment]
Reopen this bad boy

**Review by CurtisMIT — APPROVED** [review]
LGTM!

**Comment by peterghrong** [comment]
Merci

**Pull request merged**
